---
dist: xenial
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
notifications:
  email: false
